/*
 * ============================================================================
 * GNU General Public License
 * ============================================================================
 *
 * Copyright (C) 2026 Radix IoT LLC. All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * When signing a commercial license with Radix IoT LLC,
 * the following extension to GPL is made. A special exception to the GPL is
 * included to allow you to distribute a combined work that includes BAcnet4J
 * without being obliged to provide the source code for any proprietary components.
 *
 * See www.radixiot.com for commercial license options.
 */

package com.serotonin.bacnet4j.npdu.sc;

import java.security.KeyPair;
import java.security.PrivateKey;
import java.security.cert.X509Certificate;

import com.serotonin.bacnet4j.obj.SecureConnectNetworkPortObject;

/**
 * Manages the private/public key pairs of a BACnet/SC port. A port can hold up to two pairs at a time:
 * <ul>
 *   <li>The <b>active</b> pair, which matches the operational certificate currently in use.</li>
 *   <li>An optional <b>pending</b> pair, generated by the most recent GENERATE_CSR_FILE command (clause
 *       12.56.16) and awaiting the operational certificate that the signing CA produces from the CSR.</li>
 * </ul>
 * Clause 12.56.100 requires a written operational certificate to validate against "an internal private key",
 * i.e. against either of these pairs: the pending pair for a key rotation, or the active pair for a renewal
 * that reuses the existing key.
 * <p>
 * The handler is created by the product before the {@link SCNetwork} and the
 * {@link SecureConnectNetworkPortObject}, and is passed to both. The network reads from it once at TLS
 * initialization ({@link #privateKeyFor(X509Certificate)}); the port object drives the lifecycle
 * ({@link #setPendingKeyPair(KeyPair)} on CSR generation, {@link #matches(X509Certificate)} during
 * VALIDATE_CHANGES, {@link #certificateActivated(X509Certificate)} when pending changes are applied).
 * <p>
 * Implementations are responsible for persistence. Both pairs must survive a device restart: the active pair
 * because the port cannot connect without it, and the pending pair because the CSR may still be at the signing
 * CA — losing it would force the CSR round-trip to be redone. See {@link InMemoryKeyPairHandler} for a
 * non-persistent reference implementation.
 */
public interface SCKeyPairHandler {
    /**
     * Returns the key pair matching the active operational certificate. Never null.
     */
    KeyPair getActiveKeyPair();

    /**
     * Returns the pair generated for an outstanding CSR, or null if there is none.
     */
    KeyPair getPendingKeyPair();

    /**
     * Retains and persists a newly generated pair, replacing any previous pending pair (a new CSR supersedes
     * the old one). Called by the port object's GENERATE_CSR_FILE handling.
     */
    void setPendingKeyPair(KeyPair keyPair);

    /**
     * Notification that the given operational certificate became effective. If the certificate matches the
     * pending pair, the implementation should promote that pair to active, persist the promotion, and clear
     * the pending pair. If the certificate matches the active pair (a renewal without key rotation), nothing
     * needs to change and any pending pair is left in place.
     */
    void certificateActivated(X509Certificate certificate);

    /**
     * Returns true if the certificate's public key matches the active or the pending pair. Used for clause
     * 12.56.100's "operational certificate failed to validate against an internal private key" check.
     */
    default boolean matches(X509Certificate certificate) {
        return SCNetworkUtils.publicKeyMatches(certificate, getActiveKeyPair())
                || SCNetworkUtils.publicKeyMatches(certificate, getPendingKeyPair());
    }

    /**
     * Returns the private key whose public half matches the certificate, or null if neither pair matches.
     * The active pair is preferred when both match.
     */
    default PrivateKey privateKeyFor(X509Certificate certificate) {
        KeyPair active = getActiveKeyPair();
        if (SCNetworkUtils.publicKeyMatches(certificate, active)) {
            return active.getPrivate();
        }
        KeyPair pending = getPendingKeyPair();
        if (SCNetworkUtils.publicKeyMatches(certificate, pending)) {
            return pending.getPrivate();
        }
        return null;
    }
}
